name: pointnet-shape-analysis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.5.1
  - torchvision
  - pytorch-cuda=12.4
  - fvcore
  - iopath
  - pip
  - pip:
      - h5py
      - matplotlib
      - numpy
      - pyyaml
      - tqdm
